
name: Build and publish to Pastebin (develop)

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lua/LuaJIT
        uses: leafo/gh-actions-lua@v10.0.0

      - name: Run a one-line script
        run: lua ./team-turtles/build.lua
